[package]
name = "async-graphql"
version = "2.0.0-alpha.8"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"
description = "A GraphQL server library implemented in Rust"
publish = true
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[features]
default = ["apollo_tracing", "bson", "chrono", "chrono-tz", "log", "multipart", "tracing", "url"]
apollo_tracing = ["chrono"]
multipart = ["multer", "bytes", "tempfile"]
# Used for doc(cfg())
nightly = []

[dependencies]
async-graphql-derive = { path = "derive", version = "2.0.0-alpha.8" }
async-graphql-parser = { path = "parser", version = "2.0.0-alpha.8" }

async-stream = "0.3"
async-trait = "0.1.30"
fnv = "1.0.6"
futures = "0.3.5"
indexmap = "1.3.2"
itertools = "0.9.0"
once_cell = "1.3.1"
pin-project-lite = "0.1.7"
regex = "1.3.5"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
spin = "0.5.2"
thiserror = "1.0.11"
uuid = { version = "0.8.1", features = ["v4", "serde"] }

# Feature optional dependencies
bson = { version = "1.0.0", optional = true }
chrono = { version = "0.4.15", optional = true }
chrono-tz = { version = "0.5.1", optional = true }
log = { version = "0.4.11", optional = true }
tracing = { version = "0.1.19", optional = true }
url = { version = "2.1.1", optional = true }

bytes = { version = "0.5.4", optional = true }
multer = { version = "1.2.2", optional = true }
tempfile = { version = "3.1.0", optional = true }

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }

[package.metadata.docs.rs]
features = ["nightly"]

[workspace]
members = [
    "parser",
    "derive",
    "integrations/actix-web",
    "integrations/warp",
    "integrations/tide",
    "integrations/rocket",
    "benchmark",
]
