[package]
name = "async-graphql"
version = "1.18.1"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"
description = "A GraphQL server library implemented in Rust"
publish = true
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]
readme = "README.md"

[features]
default = ["bson", "url", "chrono-tz"]

[dependencies]
async-graphql-derive = { path = "derive", version = "1.18.0" }
async-graphql-parser = { path = "parser", version = "1.18.0" }

async-stream = "0.2.1"
async-trait = "0.1.30"
bytes = "0.5.4"
chrono = "0.4.10"
fnv = "1.0.6"
futures = "0.3.5"
http = "0.2.1"
httparse = "1.3.4"
indexmap = "1.3.2"
itertools = "0.9.0"
log = "0.4.8"
multer = "1.2.2"
once_cell = "1.3.1"
parking_lot = "0.10.0"
regex = "1.3.5"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
slab = "0.4.2"
spin = "0.5.2"
tempfile = "3.1.0"
thiserror = "1.0.11"
tracing = "0.1.13"
uuid = { version = "0.8.1", features = ["v4", "serde"] }

bson = { version = "1.0.0", optional = true }
url = { version = "2.1.1", optional = true }
chrono-tz = { version = "0.5.1", optional = true }


[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }

[workspace]
members = [
    "parser",
    "derive",
    "integrations/actix-web",
    "integrations/warp",
    "integrations/tide",
    "integrations/rocket",
#    "integrations/lambda",
    "benchmark",
]
