[package]
name = "async-graphql-rocket"
version = "2.0.8"
authors = ["Daniel Wiesenberg <daniel@simplificAR.io>"]
edition = "2018"
description = "async-graphql for Rocket.rs"
# Waiting for Rocket 0.5 release.
publish = false
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql", "rocket"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-graphql = { path = "../..", version = "=2.8.5" }

#rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "2893ce7", default-features = false } # TODO: Change to Cargo crate when Rocket 0.5.0 is released
rocket = { git = "https://github.com/Weasy666/Rocket", default-features = false }
serde = "1.0.125"
serde_json = "1.0.64"
tokio-util = { version = "0.6.5", default-features = false, features = ["compat"] }
