[package]
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
categories = ["network-programming", "asynchronous"]
description = "async-graphql for actix-web"
documentation = "https://docs.rs/async-graphql-actix-web/"
edition = "2021"
homepage = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
license = "MIT/Apache-2.0"
name = "async-graphql-actix-web"
repository = "https://github.com/async-graphql/async-graphql"
version = "4.0.2"

[dependencies]
async-graphql = { path = "../..", version = "4.0.1" }

actix = "0.13.0"
actix-http = "3.0.1"
actix-web = { version = "4.0.1", default-features = false }
actix-web-actors = "4.1.0"
async-channel = "1.6.1"
futures-channel = "0.3.13"
futures-util = { version = "0.3.0", default-features = false }
serde_cbor = { version = "0.11.2", optional = true }
serde_json = "1.0.64"
serde_urlencoded = "0.7.0"
thiserror = "1.0.30"

[features]
cbor = ["serde_cbor"]
default = []

[dev-dependencies]
actix-rt = "2.6.0"
async-mutex = "1.4.0"
serde = { version = "1", features = ["derive"] }
