[package]
name = "async-graphql-actix-web"
version = "2.9.14"
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
edition = "2018"
description = "async-graphql for actix-web"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql-actix-web/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-graphql = { path = "../..", version = "=2.9.14" }
actix = "0.12.0"
actix-http = "3.0.0-beta.8"
actix-web = { version = "4.0.0-beta.8", default-features = false }
actix-web-actors = "4.0.0-beta.6"
async-channel = "1.6.1"
futures-util = { version = "0.3.13", default-features = false }
serde_json = "1.0.64"
serde_urlencoded = "0.7.0"

[dev-dependencies]
actix-rt = "2.2.0"
async-mutex = "1.4.0"
