[package]
name = "async-graphql-actix-web"
version = "3.0.21"
authors = ["sunli <scott_s829@163.com>", "Koxiaet"]
edition = "2021"
description = "async-graphql for actix-web"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/async-graphql-actix-web/"
homepage = "https://github.com/async-graphql/async-graphql"
repository = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql"]
categories = ["network-programming", "asynchronous"]

[dependencies]
async-graphql = { path = "../..", version = "3.0.21" }

actix = "0.12.0"
actix-http = "3.0.0-beta.17"
actix-web = { version = "4.0.0-beta.19", default-features = false }
actix-web-actors = "4.0.0-beta.9"
async-channel = "1.6.1"
futures-util = { version = "0.3.0", default-features = false }
serde_json = "1.0.64"
serde_urlencoded = "0.7.0"
futures-channel = "0.3.13"
thiserror = "1.0.30"
serde_cbor = { version = "0.11.2", optional = true }

[features]
default = []
cbor = ["serde_cbor"]

[dev-dependencies]
actix-rt = "2.2.0"
async-mutex = "1.4.0"
serde = { version = "1", features = ["derive"] }
