[package]
authors = ["sunli <scott_s829@163.com>"]
categories = ["network-programming", "asynchronous"]
description = "async-graphql for axum"
documentation = "https://docs.rs/async-graphql-axum/"
edition = "2021"
homepage = "https://github.com/async-graphql/async-graphql"
keywords = ["futures", "async", "graphql", "axum"]
license = "MIT/Apache-2.0"
name = "async-graphql-axum"
repository = "https://github.com/async-graphql/async-graphql"
version = "5.0.0"

[dependencies]
async-graphql = { path = "../..", version = "5.0.0", default-features = false }

async-trait = "0.1.51"
axum = { version = "0.6.0", features = ["ws", "headers"] }
bytes = "1.0.1"
futures-util = "0.3.0"
http-body = "0.4.2"
serde_json = "1.0.66"
tokio-util = { version = "0.7.1", features = ["io", "compat"] }
tower-service = "0.3"
